from django.conf.urls import url
from .views import (
    view_event,
    register_to_event,
    create_or_modify_event,
    administer_event,
    preregistrations_list,
    participants_list,
    check_in,
    all_unapproved_events,
    approve_event,
    unapprove_event,
    register_as_reserve,
    CSV_view_participants,
    CSV_view_preregistrations,
    unregister,
    event_calender,
    reserves_list,
    registered_on_events,
    events_by_user,
    speech_nr_list,
    speaker_list,
    speaker_list_display,
    administer_speaker_list,
    import_registrations,
)

urlpatterns = [
    url(r'(?P<pk>[0-9]+)/$', view=view_event, name="event"),
    url(r'create_event/$', view=create_or_modify_event, name="create event"),
    url(r'(?P<pk>[0-9]+)/edit/$', view=create_or_modify_event, name="edit event"),
    url(r'(?P<pk>[0-9]+)/register/$', view=register_to_event, name="register_to_event"),
    url(r'(?P<pk>[0-9]+)/register_reserve/$', view=register_as_reserve, name="register_as_reserve"),
    url(r'(?P<pk>[0-9]+)/unregister/$', view=unregister, name="unregister"),
    url(r'(?P<pk>[0-9]+)/administer/$', view=administer_event, name="administer_event"),
    url(r'(?P<pk>[0-9]+)/administer/preregistrations/$', view=preregistrations_list, name="event_preregistrations"),
    url(r'(?P<pk>[0-9]+)/administer/participants/$', view=participants_list, name="event_participants"),
    url(r'(?P<pk>[0-9]+)/administer/import_preregistrations/$', view=import_registrations, name="import_registrations"),
    url(r'(?P<pk>[0-9]+)/administer/speech_nr_list/$', view=speech_nr_list, name="event_speech_nr_list"),
    url(r'(?P<pk>[0-9]+)/administer/reserves/$', view=reserves_list, name="event_reserves"),
    url(r'(?P<pk>[0-9]+)/administer/participants/download/$', view=CSV_view_participants, name="event_participants_download"),
    url(r'(?P<pk>[0-9]+)/administer/preregistrations/download/$', view=CSV_view_preregistrations, name="event_preregistrations_download"),
    url(r'(?P<pk>[0-9]+)/administer/event_check_in/$', view=check_in, name="event_check_in"),
    url(r'^unapproved/$', view=all_unapproved_events, name='unapproved events'),
    url(r'^(?P<event_id>[0-9]+)/approve$', view=approve_event, name='approve event'),
    url(r'^(?P<event_id>[0-9]+)/unapprove$', view=unapprove_event, name='unapprove event'),
    url(r'^calender/$', view=event_calender, name='event_calender'),
    url(r'^user_entries/$', view=registered_on_events, name='registered_on_events'),
    url(r'^my_events/$', view=events_by_user, name='events by user'),
    url(r'(?P<pk>[0-9]+)/administer/speaker/$', view=administer_speaker_list, name="event administer speaker list"),
    url(r'(?P<pk>[0-9]+)/administer/speaker/display/$', view=speaker_list_display, name="event speaker display"),
    url(r'(?P<pk>[0-9]+)/administer/speaker/list/$', view=speaker_list, name="event speaker list"),
]
