# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20151110_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsored',
            field=models.BooleanField(default=False, verbose_name='Sponsrat innehåll?'),
        ),
    ]
