# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20151217_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organisations',
            field=models.ManyToManyField(blank=True, default=None, help_text='Organisation(er) som arrangerar evenemanget. Medlemmar i dessa kan senare ändra eventet. Håll ner Ctrl för att markera flera.', to='organisations.Organisation', verbose_name='arrangör'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Håll ner Ctrl för att markera flera.', to='tags.Tag', verbose_name='tag'),
        ),
    ]
