# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20151223_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, help_text='Bifogad fil för event', null=True, upload_to='event_attachments', verbose_name='Bifogad fil'),
        ),
    ]
