#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries

# Set envrionment variables in data folder, if any. 

if [ -f $OPENSHIFT_DATA_DIR"custom_environment_variables.sh" ]; then
	sh $OPENSHIFT_DATA_DIR"customer_environment_variables.sh"
fi

