# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20151129_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedcosttemplate',
            name='add_tax',
        ),
        migrations.AlterField(
            model_name='fixedcosttemplate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='belopp ink moms'),
        ),
        migrations.AlterField(
            model_name='fixedcosttemplate',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='momssats'),
        ),
    ]
