# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20151223_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablecosttemplate',
            name='add_tax',
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='OCR nummer'),
        ),
    ]
