# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookable_info'),
        ('bookings', '0011_auto_20151223_2313'),
    ]

    operations = [
    ]
