# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': (('unlimited_num_of_bookings', 'Unlimited number of bookings'), ('manage_bookings', 'Manage bookings')), 'verbose_name': 'bokning', 'verbose_name_plural': 'bokningar'},
        ),
    ]
