# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_auto_20151223_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Kontaktinformation för organisationen', null=True, verbose_name='Kontaktinfo'),
        ),
    ]
