# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0008_auto_20151103_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpikureSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True, verbose_name='prenumererar sedan datum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ipikureprenumeranter',
                'verbose_name': 'ipikureprenumerant',
            },
        ),
    ]
