# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0009_ipikuresubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipikuresubscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
