# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0009_auto_20151215_1801'),
        ('user_managements', '0010_auto_20151217_1904'),
    ]

    operations = [
    ]
