# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0012_auto_20151223_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iuser',
            options={'permissions': (('can_view_users', 'Can view users'),), 'verbose_name': 'användare', 'verbose_name_plural': 'användare'},
        ),
        migrations.RemoveField(
            model_name='iuser',
            name='expected_exam_year',
        ),
        migrations.AddField(
            model_name='iuser',
            name='current_year',
            field=models.CharField(choices=[('1', 'åk 1'), ('2', 'åk 2'), ('3', 'åk 3'), ('4', 'åk 4'), ('5', 'åk 5'), ('p', 'uppehåll')], default='1', max_length=1, null=True, verbose_name='nuvarande årskurs'),
        ),
        migrations.AddField(
            model_name='iuser',
            name='klass',
            field=models.CharField(choices=[('u', 'ej angivet'), ('a', 'a-klassen'), ('b', 'b-klassen'), ('c', 'c-klassen'), ('d', 'd-klassen'), ('e', 'e-klassen'), ('f', 'f-klassen'), ('x', 'ia-klassen'), ('y', 'ib-klassen')], default='u', max_length=1, null=True, verbose_name='klass'),
        ),
        migrations.AlterField(
            model_name='iuser',
            name='gender',
            field=models.CharField(choices=[('m', 'man'), ('w', 'kvinna'), ('o', 'Annat / Icke-binär'), ('u', 'Vill ej ange')], max_length=1, null=True, verbose_name='kön'),
        ),
    ]
