# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0014_auto_20151223_2340'),
        ('user_managements', '0010_auto_20151213_1805'),
    ]

    operations = [
    ]
