# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0017_auto_20160101_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Man'), ('w', 'Kvinna'), ('o', 'Annat / icke-binär'), ('u', 'Vill ej ange')], default=None, max_length=1, null=True, verbose_name='kön'),
        ),
    ]
