# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0019_auto_20160105_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='iuser',
            name='must_edit',
            field=models.BooleanField(default=True, verbose_name='Måste uppdatera info'),
        ),
    ]
