# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managements', '0020_iuser_must_edit'),
        ('user_managements', '0016_auto_20151228_1534'),
    ]

    operations = [
    ]
