# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_evaluations', '0005_auto_20151214_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='belöning'),
        ),
    ]
