# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_organisationpost'),
        ('course_evaluations', '0007_auto_20151214_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEvaluationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluate_course_text', models.TextField()),
                ('mail_to_evaluator', models.TextField()),
                ('mail_to_organisation', models.TextField()),
                ('mail_addresses_to_organisation', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
            ],
        ),
    ]
