# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_evaluations', '0008_courseevaluationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseevaluationsettings',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='evaluate_course_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='mail_addresses_to_organisation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='mail_to_evaluator',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='mail_to_organisation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.Organisation'),
        ),
    ]
