# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_evaluations', '0009_auto_20151217_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='mail_addresses_to_organisation',
            field=models.TextField(help_text='En adress per rad.', null=True),
        ),
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='mail_to_evaluator',
            field=models.TextField(help_text='Följande variabler finns att tillgå: {user} = Registrerade användarens förnamn, {period} = namnet på perioden, {year} = Året, {course} = Kursens kod och namn', null=True),
        ),
        migrations.AlterField(
            model_name='courseevaluationsettings',
            name='mail_to_organisation',
            field=models.TextField(help_text='Följande variabler finns att tillgå: {user} = Registrerade användarens fullständiga namn, {user_email} = Registrerade användarens epost, {period} = namnet på perioden, {year} = Året, {course} = Kursens kod och namn, {reward} = Den valda belöningen', null=True),
        ),
    ]
