# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_evaluations', '0010_auto_20151218_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='active',
            field=models.BooleanField(default=False, verbose_name='aktiv'),
        ),
    ]
