# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20151217_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='organisations',
            field=models.ManyToManyField(help_text='Om du väljer en organisation i listan du inte tillhör kommer du att tappa åtkomsten till artikeln. Håll ner Ctrl för att markera flera.', to='organisations.Organisation', verbose_name='organisationer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Håll ner Ctrl för att markera flera.', to='tags.Tag', verbose_name='tag'),
        ),
    ]
