# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20151223_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='organisations',
            field=models.ManyToManyField(blank=True, help_text='Om du väljer en organisation i listan du inte tillhör kommer du att tappa åtkomsten till artikeln. Håll ner Ctrl för att markera flera.', to='organisations.Organisation', verbose_name='organisationer'),
        ),
    ]
