# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_auto_20160101_1640'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='namn')),
                ('organisations', models.ManyToManyField(blank=True, default=None, help_text='Organisation(er) som äger FAQ:n. Håll ner Ctrl för att markera flera.', to='organisations.Organisation', verbose_name='Ägare')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True, verbose_name='svar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Group Header')], default=1, help_text="Only questions with their status set to 'Active' will be displayed. Questions marked as 'Group Header' are treated as such by views and templates that are set up to use them.", verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='fråga'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='faq.Topic', verbose_name='ämne'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=150, verbose_name='namn'),
        ),
        migrations.AddField(
            model_name='topic',
            name='faq',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='faq.FAQ', verbose_name='FAQ'),
        ),
    ]
